### ISSUE TITLE
Createt $curHocr is named bad

### ISSUE THREAD

**Issue by kreditorro** [fritz-hh/OCRmyPDF#101]
Hello everyone

Checking if all dependencies are installed:

OCRmyPDF version: v2.0-stable
Arguments: -vvvv -d -c -f input/test.pdf output/test.pdf
Checking if all dependencies are installed
--------------------------------
ImageMagick version:
Version: ImageMagick 6.7.7-10 2014-03-06 Q16 http://www.imagemagick.org
Copyright: Copyright (C) 1999-2012 ImageMagick Studio LLC
Features: OpenMP

--------------------------------
GNU Parallel version:
GNU parallel 20130922
Copyright (C) 2007,2008,2009,2010,2011,2012,2013 Ole Tange and Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
GNU parallel comes with no warranty.

Web site: http://www.gnu.org/software/parallel

When using GNU Parallel for a publication please cite:

O. Tange (2011): GNU Parallel - The Command-Line Power Tool,
;login: The USENIX Magazine, February 2011:42-47.
--------------------------------
Poppler-utils version:
pdfimages version 0.24.5
Copyright 2005-2013 The Poppler Developers - http://poppler.freedesktop.org
Copyright 1996-2011 Glyph & Cog, LLC
pdftoppm version 0.24.5
Copyright 2005-2013 The Poppler Developers - http://poppler.freedesktop.org
Copyright 1996-2011 Glyph & Cog, LLC
pdffonts version 0.24.5
Copyright 2005-2013 The Poppler Developers - http://poppler.freedesktop.org
Copyright 1996-2011 Glyph & Cog, LLC
--------------------------------
unpaper version:
0.4.2
--------------------------------
tesseract version:
tesseract 3.02.02
 leptonica-1.69
  libjpeg 8d : libpng 1.2.50 : libtiff 4.0.3 : zlib 1.2.8

--------------------------------
python2 version:
Python 2.7.6
--------------------------------
Ghostscript version:
9.10
--------------------------------
Java version:
java version "1.6.0_33"
OpenJDK Runtime Environment (IcedTea6 1.13.5) (6b33-1.13.5-1ubuntu0.14.04)
OpenJDK 64-Bit Server VM (build 23.25-b01, mixed mode)
--------------------------------
Created temporary folder: "/tmp/tmp.P0Mzz55K7N"
Input file: Extracting size of each page (in pt)
Processing page 0001 / 0004
Page 0001: Size 841x595 (h*w in pt)
Page 0001: Expecting exactly 1 image covering the whole page (found 10). Cannot compute dpi value.
Page 0001: Continuing anyway, assuming a default resolution of 300 dpi
Page 0001: Extracting image as ppm file (300 dpi)
Page 0001: Deskewing image
Page 0001: Cleaning image with unpaper
Page 0001: Performing OCR
Page 0001: Embedding text in PDF
Could not create PDF file from "/tmp/tmp.P0Mzz55K7N/0001.hocr". Exiting...
mv: cannot stat ‘/tmp/tmp.P0Mzz55K7N/0001.hocr.html’: No such file or directory
Traceback (most recent call last):
  File "./src/hocrTransform.py", line 281, in <module>
    hocr = hocrTransform(args.hocrfile, args.resolution)
  File "./src/hocrTransform.py", line 110, in __init__
    self.hocr.parse(hocrFileName)
  File "lxml.etree.pyx", line 1791, in lxml.etree._ElementTree.parse (src/lxml/lxml.etree.c:54431)
  File "parser.pxi", line 1748, in lxml.etree._parseDocument (src/lxml/lxml.etree.c:102066)
  File "parser.pxi", line 1774, in lxml.etree._parseDocumentFromURL (src/lxml/lxml.etree.c:102330)
  File "parser.pxi", line 1678, in lxml.etree._parseDocFromFile (src/lxml/lxml.etree.c:101365)
  File "parser.pxi", line 1110, in lxml.etree._BaseParser._parseDocFromFile (src/lxml/lxml.etree.c:96817)
  File "parser.pxi", line 582, in lxml.etree._ParserContext._handleParseResultDoc (src/lxml/lxml.etree.c:91275)
  File "parser.pxi", line 683, in lxml.etree._handleParseResult (src/lxml/lxml.etree.c:92461)
  File "parser.pxi", line 620, in lxml.etree._raiseParseError (src/lxml/lxml.etree.c:91722)
IOError: Error reading file '/tmp/tmp.P0Mzz55K7N/0001.hocr': failed to load external entity "/tmp/tmp.P0Mzz55K7N/0001.hocr"
parallel: Starting no more jobs. Waiting for 2 jobs to finish. This job failed:
./src/ocrPage.sh /home/testuser.ocr/input/test.pdf 0001\ 595\ 841 0004 /tmp/tmp.P0Mzz55K7N 4 eng 0 1 1 0 0 0 '' 1
Processing page 0002 / 0004
Page 0002: Size 841x595 (h*w in pt)
Page 0002: Expecting exactly 1 image covering the whole page (found 29). Cannot compute dpi value.
Page 0002: Continuing anyway, assuming a default resolution of 300 dpi
Page 0002: Extracting image as ppm file (300 dpi)
Page 0002: Deskewing image
Page 0002: Cleaning image with unpaper
Page 0002: Performing OCR
Page 0002: Embedding text in PDF
Could not create PDF file from "/tmp/tmp.P0Mzz55K7N/0002.hocr". Exiting...
mv: cannot stat ‘/tmp/tmp.P0Mzz55K7N/0002.hocr.html’: No such file or directory
Traceback (most recent call last):
  File "./src/hocrTransform.py", line 281, in <module>
    hocr = hocrTransform(args.hocrfile, args.resolution)
  File "./src/hocrTransform.py", line 110, in __init__
    self.hocr.parse(hocrFileName)
  File "lxml.etree.pyx", line 1791, in lxml.etree._ElementTree.parse (src/lxml/lxml.etree.c:54431)
  File "parser.pxi", line 1748, in lxml.etree._parseDocument (src/lxml/lxml.etree.c:102066)
  File "parser.pxi", line 1774, in lxml.etree._parseDocumentFromURL (src/lxml/lxml.etree.c:102330)
  File "parser.pxi", line 1678, in lxml.etree._parseDocFromFile (src/lxml/lxml.etree.c:101365)
  File "parser.pxi", line 1110, in lxml.etree._BaseParser._parseDocFromFile (src/lxml/lxml.etree.c:96817)
  File "parser.pxi", line 582, in lxml.etree._ParserContext._handleParseResultDoc (src/lxml/lxml.etree.c:91275)
  File "parser.pxi", line 683, in lxml.etree._handleParseResult (src/lxml/lxml.etree.c:92461)
  File "parser.pxi", line 620, in lxml.etree._raiseParseError (src/lxml/lxml.etree.c:91722)
IOError: Error reading file '/tmp/tmp.P0Mzz55K7N/0002.hocr': failed to load external entity "/tmp/tmp.P0Mzz55K7N/0002.hocr"
parallel: Starting no more jobs. Waiting for 1 jobs to finish. This job failed:
./src/ocrPage.sh /home/testuser.ocr/input/test.pdf 0002\ 595\ 841 0004 /tmp/tmp.P0Mzz55K7N 4 eng 0 1 1 0 0 0 '' 1

tmp-Folder:
0001.cleaned.ppm       0002.orig-img-000.jpg  0002.orig-img-017.pbm
0001.deskewed.ppm      0002.orig-img-001.pbm  0002.orig-img-018.pbm
0001.hocr.txt          0002.orig-img-002.pbm  0002.orig-img-019.pbm
0001.orig-img-000.jpg  0002.orig-img-003.pbm  0002.orig-img-020.pbm
0001.orig-img-001.pbm  0002.orig-img-004.pbm  0002.orig-img-021.pbm
0001.orig-img-002.pbm  0002.orig-img-005.pbm  0002.orig-img-022.pbm
0001.orig-img-003.pbm  0002.orig-img-006.pbm  0002.orig-img-023.pbm
0001.orig-img-004.pbm  0002.orig-img-007.pbm  0002.orig-img-024.pbm
0001.orig-img-005.pbm  0002.orig-img-008.pbm  0002.orig-img-025.pbm
0001.orig-img-006.pbm  0002.orig-img-009.pbm  0002.orig-img-026.pbm
0001.orig-img-007.pbm  0002.orig-img-010.pbm  0002.orig-img-027.pbm
0001.orig-img-008.pbm  0002.orig-img-011.pbm  0002.orig-img-028.pbm
0001.orig-img-009.pbm  0002.orig-img-012.pbm  0002.ppm
0001.ppm               0002.orig-img-013.pbm  pages-info.txt
0002.cleaned.ppm       0002.orig-img-014.pbm  tmp.txt
0002.deskewed.ppm      0002.orig-img-015.pbm
0002.hocr.txt          0002.orig-img-016.pbm

I think the problem is the 0001.hocr.txt file, which is probably false named.
I read the https://github.com/fritz-hh/OCRmyPDF/issues/72 but it dont work, because after editing the $curHocr, the skript ist searching for a .hocr.hocr instead of .hocr.html, and this dont fix the .hocr.txt problem ^^

Regards
kreditorro

**Comment by jbarlow83** [comment]
Please try again in v3.0-rc2.
