### ISSUE TITLE
Feedback on Debian Wheezy

### ISSUE THREAD

**Issue by saintger** [fritz-hh/OCRmyPDF#102]
Hi,,
Thanks for this nice piece of software.

Here is a few feedback from my experience with Debian Wheezy:
 - Tesseract 3.02.01-6 is on Debian Wheezy but it is currently being identified as 3.02 (tesseract -v). So OCRmyPDF detect it as 3.02 but requires 3.02.01
  - Tesseract 3.02.01-6 doesn't have a --list-langs
  - Trying to use OCRmyPDF inside a virtualenv failed because OCRmyPDF call directly python2 instead of python

So it works on Debian Wheezy, except that I had to install "parallel" from Jessie (version on Wheezy is too old). The only problem I had is bug #28 but it is expected.

Hope that help !

**Comment by jbarlow83** [comment]
OCRmyPDF v3.0-rc2 should work with virtualenv now. I think we ran into other problems with Tesseract <= 3.02.02 so that is still the minimum.
