### ISSUE TITLE
Poor OCR Results

### ISSUE THREAD

**Issue by Manuel-J** [fritz-hh/OCRmyPDF#103]
Hi,

this is maybe not an issue of ocrmypdf but when I have tried this great looking script it produced only quite poor results:
e.g.: http://www.file-upload.net/download-10212036/test1_ocr.pdf.html
original: http://www.spiegel.de/media/media-33991.pdf 
May I expect a better OCR result?

Cheers,
  Manuel

```
./OCRmyPDF.sh -g -o 300 test1.pdf test1_ocr.pdf
OCRmyPDF version: v2.2-stable
Arguments: -g -o 300 test1.pdf test1_ocr.pdf
Checking if all dependencies are installed
--------------------------------
ImageMagick version:
Version: ImageMagick 6.6.9-7 2014-03-06 Q16 http://www.imagemagick.org
Copyright: Copyright (C) 1999-2011 ImageMagick Studio LLC
Features: OpenMP

--------------------------------
GNU Parallel version:
WARNING: YOU ARE USING --tollef. IF THINGS ARE ACTING WEIRD USE --gnu.
GNU parallel 20121122
Copyright (C) 2007,2008,2009,2010,2011,2012 Ole Tange and Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
GNU parallel comes with no warranty.

Web site: http://www.gnu.org/software/parallel

When using GNU Parallel for a publication please cite:

O. Tange (2011): GNU Parallel - The Command-Line Power Tool,
;login: The USENIX Magazine, February 2011:42-47.
--------------------------------
Poppler-utils version:
pdfimages version 0.18.4
Copyright 2005-2011 The Poppler Developers - http://poppler.freedesktop.org
Copyright 1996-2004 Glyph & Cog, LLC
pdftoppm version 0.18.4
Copyright 2005-2011 The Poppler Developers - http://poppler.freedesktop.org
Copyright 1996-2004 Glyph & Cog, LLC
pdffonts version 0.18.4
Copyright 2005-2011 The Poppler Developers - http://poppler.freedesktop.org
Copyright 1996-2004 Glyph & Cog, LLC
--------------------------------
unpaper version:
0.3
--------------------------------
tesseract version:
tesseract 3.02.02
 leptonica-1.71
  libjpeg 8b : libpng 1.2.46 : libtiff 3.9.5 : zlib 1.2.3.4

--------------------------------
python2 version:
Python 2.7.3
--------------------------------
Ghostscript version:
9.05
--------------------------------
Java version:
java version "1.7.0_76"
Java(TM) SE Runtime Environment (build 1.7.0_76-b13)
Java HotSpot(TM) 64-Bit Server VM (build 24.76-b04, mixed mode)
--------------------------------
Created temporary folder: "/tmp/tmp.yvnBCpiQtN"
Input file: Extracting size of each page (in pt)
Processing page 0001 / 0001
Page 0001: Size 791x611 (h*w in pt)
Page 0001: Size 1099x849 (in pixel)
Page 0001: Low image resolution detected (100 dpi). Performing oversampling (300 dpi) to try to get better OCR results.
Page 0001: Extracting image as ppm file (300 dpi)
Page 0001: Performing OCR
Page 0001: Embedding text in PDF
Page 0001: Embedding text in PDF (debug page)
Output file: Concatenating all pages to the final PDF/A file
Output file: Checking compliance to PDF/A standard
The full validation log is available here: "/tmp/tmp.yvnBCpiQtN/pdf_validation.log"
Output file: The generated PDF/A file is VALID
Script took 11 seconds
```

**Comment by fritz-hh** [comment]
Hi Manuel,

Thanks for your message.
The file "http://www.spiegel.de/media/media-33991.pdf " does not seem to be the original.
(The content is completely different and furthermore it does not contain images but already fonts)
Could you please provide the original file.

Thanks

**Comment by Manuel-J** [comment]
Hi Fritz,

thank you for your fast response.
Sorry that I have mixed up my test files, here you can find the original one for the shown "test case":
http://www.spiegel.de/media/media-34034.pdf

Thanks,
   Manuel

**Comment by fritz-hh** [comment]
Accroding to me, there are various factors that lead to this result:
- The document seems to contain an image having 100dpi. This is too low to expect very good results 
- The document contains various words that are in no dictionnary (e.g. "(S//SI//REL)") and are therefore very difficult to recognize (tesseract first analyzes the layout, then tries to identify the characters and then uses a dictionnary to improve the results) (note: that is why it is important to tell ocrmypdf in which language the doc is written)
- The document contains black rectangles

I fear that it will be difficult to get good results with the underlying ocr engine (tesseract) with this document

**Comment by femifrak** [comment]
Hi,

i am happy to read from you, fritz-hh. This shows me that you are still working on ocrmypdf. As i did not find any posting from you at the near past, i feared that you stopped developing ocrmypdf. That would have been a great pity. (This is meant to be an encouragement. :-) ) 
Thanks for your work until now and good luck for the future,

Femi

**Comment by mlissner** [comment]
This looks like an issue that should be easy to close.
