### ISSUE TITLE
No output pdf file

### ISSUE THREAD

**Issue by sjoswig** [fritz-hh/OCRmyPDF#110]
I'm using ocrmypdf 2.1.0-1 on my arch and the last weeks I had no problem get ocr out of pdfs correctly with ocrmypdf, but no only temporary files were created and no single output pdf.

Here is the log file:

`OCRmyPDF version: v2.1-stable
Arguments: -f -vvv -l deu 2015-03-13 Kraftfahrtversicherung_ohne.pdf /home/js/Share/2015-03-13 Kraftfahrtversicherung.pdf
Checking if all dependencies are installed
--------------------------------
ImageMagick version:
Version: ImageMagick 6.9.1-8 Q16 x86_64 2015-07-14 http://www.imagemagick.org
Copyright: Copyright (C) 1999-2015 ImageMagick Studio LLC
License: http://www.imagemagick.org/script/license.php
Features: Cipher DPC HDRI Modules OpenCL OpenMP 
Delegates (built-in): bzlib cairo fontconfig freetype gslib jng jp2 jpeg lcms lqr ltdl lzma pangocairo png ps rsvg tiff webp wmf x xml zlib

--------------------------------
GNU Parallel version:
GNU parallel 20150622
Copyright (C) 2007,2008,2009,2010,2011,2012,2013,2014,2015 Ole Tange
and Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
GNU parallel comes with no warranty.

Web site: http://www.gnu.org/software/parallel

When using programs that use GNU Parallel to process data for publication
please cite as described in 'parallel --bibtex'.
--------------------------------
Poppler-utils version:
pdfimages version 0.33.0
Copyright 2005-2015 The Poppler Developers - http://poppler.freedesktop.org
Copyright 1996-2011 Glyph & Cog, LLC
pdftoppm version 0.33.0
Copyright 2005-2015 The Poppler Developers - http://poppler.freedesktop.org
Copyright 1996-2011 Glyph & Cog, LLC
pdffonts version 0.33.0
Copyright 2005-2015 The Poppler Developers - http://poppler.freedesktop.org
Copyright 1996-2011 Glyph & Cog, LLC
--------------------------------
unpaper version:
6.1
--------------------------------
tesseract version:
tesseract 3.04.00
 leptonica-1.71
  libgif 5.1.0 : libjpeg 8d : libpng 1.6.16 : libtiff 4.0.4 : zlib 1.2.8 : libwebp 0.4.3

--------------------------------
python2 version:
Python 2.7.10
--------------------------------
Ghostscript version:
9.16
--------------------------------
Java version:
java version "1.8.0_51"
Java(TM) SE Runtime Environment (build 1.8.0_51-b16)
Java HotSpot(TM) 64-Bit Server VM (build 25.51-b03, mixed mode)
--------------------------------
Created temporary folder: "/tmp/tmp.XZtlIvt11N"
Input file: Extracting size of each page (in pt)
Processing page 0001 / 0001
Page 0001: Size 842x596 (h*w in pt)
Page 0001: Size 2482x3510 (in pixel)
Page 0001: Extracting image as pbm file (300 dpi)
Page 0001: Performing OCR
Page 0001: Embedding text in PDF`

**Comment by sjoswig** [comment]
Tested with fresh downloaded latest stable version. Same result. In the example above the origin pdf file has four slides.

**Comment by sjoswig** [comment]
Works with docker based OCRmyPDF.

**Comment by frhd** [comment]
Same issue on OS X yosemite, no output file.

**Comment by jbarlow83** [comment]
Please try the new version (3.0) instead. https://github.com/fritz-hh/OCRmyPDF/tree/master
