### ISSUE TITLE
Installation issues. i) root required ii) pip3 install -e . fails because it cannot find tesseract

### ISSUE THREAD

**Issue by Wikinaut** [fritz-hh/OCRmyPDF#112]
Let me report two installation issues which stops from currently from building and running the OCRmyPDF.

1.

Trying to install with ```pip3 install -e .```. Then it says
```
running install_lib
    creating /usr/lib/python3.4/site-packages/ruffus
    error: could not create '/usr/lib/python3.4/site-packages/ruffus': Permission denied
```

At least this step appear to require root user for the command ```sudo pip3 install -e .``` which - if my observation is correct - should be mentioned in the README.

2.
Running it again then fails with
```
The program 'tesseract' could not be executed or was not found on your system PATH.
```
However, tesseract is present on my system (/usr/local/bin/tesseract), and also the tessdata languages are present ( TESSDATA_PREFIX=/usr/local/src/tesseract/tessdata).
 
What else can be wrong or missing so that OCRmyPDF shows the error ?

**Comment by jbarlow83** [comment]
What OS are you using?

What's the output of `tesseract --version`?

**Comment by jbarlow83** [comment]
Also note I *just* released a new update that has better installation instructions in reference to your first issue. I didn't change anything that would affect the check for the presence of tesseract though, so I'm not expecting it to work off the bat (sorry). 

You can also bypass the tesseract test "check_external_program('tesseract', ...)" in setup.py around line 150 and see what happens.

**Comment by Wikinaut** [comment]
OS = Opensuse Tumbleweed
```
tesseract 3.05.00dev-23-gbb19f2c
 leptonica-1.72
  libgif 5.1.1 : libjpeg 6b (libjpeg-turbo 1.4.0) : libpng 1.6.17 : libtiff 4.0.4 : zlib 1.2.8
```

**Comment by Wikinaut** [comment]
I bypassed that tesseract check. Perhaps the error comes from the fact, that I have *not* installed tesseract as package but built from scratch !

Now see http://dpaste.com/02HA8QZ .

OCRmyPDF fails, looks like a beast with too many dependencies.

**Comment by jbarlow83** [comment]
Yes, that would be the case. You do realize if you're rolling your own
system packages and libraries it's pretty hard for anyone to support you,
and you do run into lots of build breakage.

It looks like GCC is missing required headers for Python extension modules.
If Suse is apt package based try apt-get install Python3-pil to get your
package manager to install PIL.

**Comment by Wikinaut** [comment]
After having installed that, and further missing lib-devel s (libxml2, libxslt), I now got
```
  building 'reportlab.lib._rl_accel' extension
    creating build/temp.linux-x86_64-3.4
    creating build/temp.linux-x86_64-3.4/tmp
    creating build/temp.linux-x86_64-3.4/tmp/pip-build-3xcikl26
    creating build/temp.linux-x86_64-3.4/tmp/pip-build-3xcikl26/reportlab
    creating build/temp.linux-x86_64-3.4/tmp/pip-build-3xcikl26/reportlab/src
    creating build/temp.linux-x86_64-3.4/tmp/pip-build-3xcikl26/reportlab/src/rl_addons
    creating build/temp.linux-x86_64-3.4/tmp/pip-build-3xcikl26/reportlab/src/rl_addons/rl_accel
    gcc -pthread -Wno-unused-result -DNDEBUG -fmessage-length=0 -grecord-gcc-switches -O2 -Wall -D_FORTIFY_SOURCE=2 -fstack-protector -funwind-tables -fasynchronous-unwind-tables -g -DOPENSSL_LOAD_CONF -fPIC -I/usr/include/python3.4m -c /tmp/pip-build-3xcikl26/reportlab/src/rl_addons/rl_accel/_rl_accel.c -o build/temp.linux-x86_64-3.4/tmp/pip-build-3xcikl26/reportlab/src/rl_addons/rl_accel/_rl_accel.o
    /tmp/pip-build-3xcikl26/reportlab/src/rl_addons/rl_accel/_rl_accel.c:8:20: fatal error: Python.h: Datei oder Verzeichnis nicht gefunden
     #include "Python.h"
                        ^
    compilation terminated.
    error: command 'gcc' failed with exit status 1
    
    ----------------------------------------
Command "/usr/bin/python3 -c "import setuptools, tokenize;__file__='/tmp/pip-build-3xcikl26/reportlab/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /tmp/pip-xf9n2m8t-record/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /tmp/pip-build-3xcikl26/reportlab

```

**Comment by jbarlow83** [comment]
Apt-get install python3-reportlab

**Comment by Wikinaut** [comment]
Not available for Opensuse Tumbleweed. Only python-reportlab is available.

**Comment by Wikinaut** [comment]
(giving up with this program)

**Comment by Wikinaut** [comment]
@jbarlow83 a short feedback:

Good news: using c14e10128a8c7f01e240e50b39b9da5cdef659b8 , I could build the program and will now start testing and using it. too.

However, because I always use the **latest** Tesseract https://github.com/tesseract-ocr/tesseract , I had again to modify setup.py as recommended by you above in https://github.com/fritz-hh/OCRmyPDF/issues/112#issuecomment-131509053 .

So I suggest to reopen this issue, and to modify the installing process, so that tesseract is correctly detected when it is installed from a package, or manually from the sources. ("tesseract --version")

`pip3 install -e .` should not fail on such "bleeding-edge" systems where `tesseract` is correctly installed from the sources, i.e. systems where tesseract is not installed via a package. 

Perhaps you can agree on this point.
