### ISSUE TITLE
OCRmyPDF-2.x$ does not pass -l language flag correctly + Resulting size of pdf is far to big

### ISSUE THREAD

**Issue by lowmaster** [fritz-hh/OCRmyPDF#117]
Hi. 
Thank you for this great app here. But my first install & try was not satisfying. 

Maybe this is an issue of the version I used. I will try other version later, however, you should notice that there might be an issue with upcoming version of tesseract:

If the image produced in the tmp folder by OCRmyPDF-2.x$ is used in tesseract only, there seem to be no issue:

tesseract 1.ppm -l deu+tur 1c.txt
or 
tesseract 1.ppm -l tur 1c.txt

Turkish letters are propperly detected.

If I pass the language in OCRmyPDF I cannot see turkish letters in the resulting pdf.
The size of the pdf is exorbitant larger.

It does not matter if I set default languages in config or not, or play with other flags like -d -i -c

./OCRmyPDF.sh -l tur -f -g 1.pdf 2b.pdf

freetz@freetz-linux:~/OCRmyPDF-2.x$ ./OCRmyPDF.sh -l tur -f -g 1.pdf 2b.pdf
OCRmyPDF version: v2.x
Arguments: -l tur -f -g 1.pdf 2b.pdf
Checking if all dependencies are installed
--------------------------------
ImageMagick version:
Version: ImageMagick 6.6.9-7 2014-03-06 Q16 http://www.imagemagick.org
Copyright: Copyright (C) 1999-2011 ImageMagick Studio LLC
Features: OpenMP

--------------------------------
GNU Parallel version:
GNU parallel 20150822
Copyright (C) 2007,2008,2009,2010,2011,2012,2013,2014,2015 Ole Tange
and Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
GNU parallel comes with no warranty.

Web site: http://www.gnu.org/software/parallel

When using programs that use GNU Parallel to process data for publication
please cite as described in 'parallel --bibtex'.
--------------------------------
Poppler-utils version:
pdfimages version 0.18.4
Copyright 2005-2011 The Poppler Developers - http://poppler.freedesktop.org
Copyright 1996-2004 Glyph & Cog, LLC
pdftoppm version 0.18.4
Copyright 2005-2011 The Poppler Developers - http://poppler.freedesktop.org
Copyright 1996-2004 Glyph & Cog, LLC
pdffonts version 0.18.4
Copyright 2005-2011 The Poppler Developers - http://poppler.freedesktop.org
Copyright 1996-2004 Glyph & Cog, LLC
pdfseparate version 0.18.4
Copyright 2005-2011 The Poppler Developers - http://poppler.freedesktop.org
Copyright 1996-2004 Glyph & Cog, LLC
--------------------------------
unpaper version:
6.1
--------------------------------
tesseract version:
tesseract 3.05.00dev
 leptonica-1.72
  libjpeg 8b (libjpeg-turbo 1.2.0) : libpng 1.2.46 : libtiff 3.9.5 : zlib 1.2.3.4

--------------------------------
python2 version:
Python 2.7.3
--------------------------------
Ghostscript version:
9.05
--------------------------------
Java version:
java version "1.6.0_36"
OpenJDK Runtime Environment (IcedTea6 1.13.8) (6b36-1.13.8-0ubuntu1~12.04)
OpenJDK Server VM (build 23.25-b01, mixed mode)
--------------------------------
Created temporary folder: "/tmp/tmp.GeLS2bVd2g"
Input file: Extracting size of each page (in pt)
Processing page 0001 / 0016
Page 0001: Size 841x595 (h*w in pt)
Page 0001: Page already contains font data !!!
Page 0001: OCRing anyway, assuming a default resolution of 300 dpi
Page 0001: Extracting image as ppm file (300 dpi)
Page 0001: Performing OCR
Page 0001: Embedding text in PDF
Page 0001: Embedding text in PDF (debug page)
Processing page 0002 / 0016
Page 0002: Size 841x595 (h*w in pt)
Page 0002: Page already contains font data !!!
Page 0002: OCRing anyway, assuming a default resolution of 300 dpi
Page 0002: Extracting image as ppm file (300 dpi)
Page 0002: Performing OCR
Page 0002: Embedding text in PDF
Page 0002: Embedding text in PDF (debug page)
Processing page 0003 / 0016
Page 0003: Size 841x595 (h*w in pt)
Page 0003: Page already contains font data !!!
Page 0003: OCRing anyway, assuming a default resolution of 300 dpi
Page 0003: Extracting image as ppm file (300 dpi)
Page 0003: Performing OCR
Page 0003: Embedding text in PDF
Page 0003: Embedding text in PDF (debug page)
Processing page 0004 / 0016
Page 0004: Size 841x595 (h*w in pt)
Page 0004: Page already contains font data !!!
Page 0004: OCRing anyway, assuming a default resolution of 300 dpi
Page 0004: Extracting image as ppm file (300 dpi)
Page 0004: Performing OCR
Page 0004: Embedding text in PDF
Page 0004: Embedding text in PDF (debug page)
Processing page 0005 / 0016
Page 0005: Size 841x595 (h*w in pt)
Page 0005: Page already contains font data !!!
Page 0005: OCRing anyway, assuming a default resolution of 300 dpi
Page 0005: Extracting image as ppm file (300 dpi)
Page 0005: Performing OCR
Page 0005: Embedding text in PDF
Page 0005: Embedding text in PDF (debug page)
Processing page 0006 / 0016
Page 0006: Size 841x595 (h*w in pt)
Page 0006: Page already contains font data !!!
Page 0006: OCRing anyway, assuming a default resolution of 300 dpi
Page 0006: Extracting image as ppm file (300 dpi)
Page 0006: Performing OCR
Page 0006: Embedding text in PDF
Page 0006: Embedding text in PDF (debug page)
Processing page 0007 / 0016
Page 0007: Size 841x595 (h*w in pt)
Page 0007: Page already contains font data !!!
Page 0007: OCRing anyway, assuming a default resolution of 300 dpi
Page 0007: Extracting image as ppm file (300 dpi)
Page 0007: Performing OCR
Page 0007: Embedding text in PDF
Page 0007: Embedding text in PDF (debug page)
Processing page 0008 / 0016
Page 0008: Size 841x595 (h*w in pt)
Page 0008: Page already contains font data !!!
Page 0008: OCRing anyway, assuming a default resolution of 300 dpi
Page 0008: Extracting image as ppm file (300 dpi)
Page 0008: Performing OCR
Page 0008: Embedding text in PDF
Page 0008: Embedding text in PDF (debug page)
Processing page 0009 / 0016
Page 0009: Size 841x595 (h*w in pt)
Page 0009: Page already contains font data !!!
Page 0009: OCRing anyway, assuming a default resolution of 300 dpi
Page 0009: Extracting image as ppm file (300 dpi)
Page 0009: Performing OCR
Page 0009: Embedding text in PDF
Page 0009: Embedding text in PDF (debug page)
Processing page 0010 / 0016
Page 0010: Size 841x595 (h*w in pt)
Page 0010: Page already contains font data !!!
Page 0010: OCRing anyway, assuming a default resolution of 300 dpi
Page 0010: Extracting image as ppm file (300 dpi)
Page 0010: Performing OCR
Page 0010: Embedding text in PDF
Page 0010: Embedding text in PDF (debug page)
Processing page 0011 / 0016
Page 0011: Size 841x595 (h*w in pt)
Page 0011: Page already contains font data !!!
Page 0011: OCRing anyway, assuming a default resolution of 300 dpi
Page 0011: Extracting image as ppm file (300 dpi)
Page 0011: Performing OCR
Page 0011: Embedding text in PDF
Page 0011: Embedding text in PDF (debug page)
Processing page 0012 / 0016
Page 0012: Size 841x595 (h*w in pt)
Page 0012: Page already contains font data !!!
Page 0012: OCRing anyway, assuming a default resolution of 300 dpi
Page 0012: Extracting image as ppm file (300 dpi)
Page 0012: Performing OCR
Page 0012: Embedding text in PDF
Page 0012: Embedding text in PDF (debug page)
Processing page 0013 / 0016
Page 0013: Size 841x595 (h*w in pt)
Page 0013: Page already contains font data !!!
Page 0013: OCRing anyway, assuming a default resolution of 300 dpi
Page 0013: Extracting image as ppm file (300 dpi)
Page 0013: Performing OCR
Page 0013: Embedding text in PDF
Page 0013: Embedding text in PDF (debug page)
Processing page 0014 / 0016
Page 0014: Size 841x595 (h*w in pt)
Page 0014: Page already contains font data !!!
Page 0014: OCRing anyway, assuming a default resolution of 300 dpi
Page 0014: Extracting image as ppm file (300 dpi)
Page 0014: Performing OCR
Page 0014: Embedding text in PDF
Page 0014: Embedding text in PDF (debug page)
Processing page 0015 / 0016
Page 0015: Size 841x595 (h*w in pt)
Page 0015: Page already contains font data !!!
Page 0015: OCRing anyway, assuming a default resolution of 300 dpi
Page 0015: Extracting image as ppm file (300 dpi)
Page 0015: Performing OCR
Page 0015: Embedding text in PDF
Page 0015: Embedding text in PDF (debug page)
Processing page 0016 / 0016
Page 0016: Size 841x595 (h*w in pt)
Page 0016: Page already contains font data !!!
Page 0016: OCRing anyway, assuming a default resolution of 300 dpi
Page 0016: Extracting image as ppm file (300 dpi)
Page 0016: Performing OCR
Page 0016: Embedding text in PDF
Page 0016: Embedding text in PDF (debug page)
Output file: Concatenating all pages to the final PDF/A file
Output file: Checking compliance to PDF/A standard
The full validation log is available here: "/tmp/tmp.GeLS2bVd2g/pdf_validation.log"
Output file: The generated PDF/A file is VALID
Script took 377 seconds

**Comment by jbarlow83** [comment]
I'm not supporting v2.x anymore (I didn't create it). Would you mind trying v3.0 and let me know what happens?
