### ISSUE TITLE
need scanning recommendation (b/w or grey)

### ISSUE THREAD

**Issue by femifrak** [fritz-hh/OCRmyPDF#121]
Hi,

i would like to scan several pages and have the possibility to scan them black and white or grey. For better reading and smaller file sizes i would clearly prefer black and white. But these three points will influence my decision. Could someone give me an advice, please?

1.) Is the recognition quality generally significantly better with grey input?

Considering the answer to 1.) is yes:
2.) Is it possible whithin ocrmypdf to use grey as input and to get b/w pdfs as output while tesseract would get grey as input?

Considering the answers to 2.) are yes/yes
3.) I would not want to adjust a b/w level manually on a per page basis (while the scanning software will set the level automatically quite reasonable.) Can ocymypdf/unpaper adjust the level to a reasonable value?

Thanks for your comments,

Femi

**Comment by jbarlow83** [comment]
I would scan at b/w. Your scanner has more data (often 12-bit input resolution that is later reduced to 8-bit) and so it can do a better job of making a good b/w scan than any software that does not have this extra information. You can often change scanning modes for a few exception pages to get them in grey/color.
1. Not necessary. Tesseract internally converts the image to b/w for recognition, but may get the threshold wrong from a grey input. Whether done in b/w or grey, what it really needs is a lot of contrast between text and background. https://github.com/tesseract-ocr/tesseract/wiki/ImproveQuality 
2. Not supported right now, but technically possible when `--pdf-renderer hocr` is used.
3. No software can binarize an image and guarantee it won't discard something important.

As for how to reduce file sizes after scanning:
- Probably the easiest way to way reduce file size would be to refry the output PDF with ghostscript at a lower resolution, `gs -sDEVICE=pdfwrite -o outputfile -r DPIxDPI inputfile`. (That will strip PDF/A in the process, but with extra effort you could get PDF/A.)
- I can still do more to improve the output file size and will do so in later releases, e.g. JBIG2 encoding.
- "pdfbeads" is similar to this project but has some different goals. It does do more to try making PDFs smaller file sizes, but it's not very robust, not maintained, and most of the documentation is in Russian.

**Comment by femifrak** [comment]
Thanks, this info helps me a lot. I will scan in b/w mode which leads to smaller file sizes as well.

One off topic remark/idea: I don't know how ocr software works but i could imagine that ocring is like optimization including an objective value. This objective value would allow quantifying how good the graphical text was recognized. With an extra loop in which the threshold is varied, one could automatically determine the optimal threshold with the best recognition quality. Just my 2 cents.

**Comment by jbarlow83** [comment]
You may be right, but your suggestion would involve running the computationally expensive part of the OCR engine multiple times per page. The Tesseract wiki has a white paper published describing its algorithm details - sounds like you might be interested in learning more about how it actually works.
