### ISSUE TITLE
Auto correct image rotation (-180, -90, 0, +90)

### ISSUE THREAD

**Issue by fritz-hh** [fritz-hh/OCRmyPDF#46]

**Comment by eloops** [comment]
I ported this to a node library ([here](https://github.com/eloops/hocr2pdf)), part of it was implementing auto-rotation. Added a prototype to find the general rotation (by finding the greatest number of textangles in the hocr). Also by climbing up/down the DOM to the ocr_line class `<span>` elements and grabbing the textangle I could correct it when writing the words to the canvas. Still not sure yet if it's faster to do a separate `-psm 0` (OSD only) and then a `-psm 6` for the OCR text or just the `-psm 1` (get everything).
