### ISSUE TITLE
Packaging and automatic dependency resolution

### ISSUE THREAD

**Issue by Treehopper** [fritz-hh/OCRmyPDF#53]
I suggest releasing packages for some of the major operating system. Package managers can then automatically resolve most of the required dependencies, and thus simplify the installation process.

I'd offer my help with setting up the packaging for Apt (Debian/Ubuntu/...).

**Comment by paulstaab** [comment]
Somewhat related: I created a [docker container for OCRmyPDF](https://registry.hub.docker.com/u/paulstaab/ocrmypdf) which should be usable on every platform that supports docker.

**Comment by 1337sup3rh4x0r** [comment]
Thank you paul! I already gave up on this due too endless dependancy resolving loops but now it just works out of the box.

**Comment by jbarlow83** [comment]
@paulstaab. Real interesting idea. I actually have a use for this - I'd like to run large batch OCR jobs on EC2 but don't want to spend my life configuring Amazon Linux images.

I get an error message when running the container:
```
parallel: Warning: $SHELL not set. Using /bin/sh.
```

`export SHELL=/bin/sh` would probably clear that up.

@1337sup3rh4x0r : I'll link to it in readme.md. Fritz is less active at the moment.

**Comment by paulstaab** [comment]
I updated the container with `SHELL` defined, the warning should now be gone.

Thanks for linking to the container in the readme!

**Comment by jbarlow83** [comment]
Done in v3.0rc2
