### ISSUE TITLE
Tesseract 3.03-rc1 and newer git versions have basic integrated(!) mixed-mode single-page PDF rendering support

### ISSUE THREAD

**Issue by Wikinaut** [fritz-hh/OCRmyPDF#85]
[UPDATED: I removed the information about the tessedit_pdf_compression parameter, which has been recently removed in the HEAD branch version of tesseract.]

#### Thanks
Dear developers of OCRmyPDF, first at all, **thank you for your impressive and great work**. 

#### News

In the meantime, after your publications in autumn 2013 and later in German magazine "c't", the Tesseract developers integrated a similar PDF output support into their code starting in February 2014, which makes - not in all, but in many standard cases - the OCRmyPDF framework obsolete, in my personal view.

The new feature can currently only be used if you checkout Tesseract from their source in Google git ( https://code.google.com/p/tesseract-ocr/ explains how)

#### Searchable PDF output is a standard feature as of Tesseract version 3.03
* https://code.google.com/p/tesseract-ocr/wiki/FAQ#How_do_I_produce_searchable_PDF_output?

```
tesseract phototest.png phototest pdf
```

#### framework for multi-page pdfs
Tesseract cannot process multi-page PDFs as input.

Here is a framework example:

* splitting (use pdftk) and converting (use convert from imagemagick) into single-page png images (lossless coded)
* per page: tesseract OCR process and create a single-page mixed-mode PDF
* merge (use pdftk) the single-page mixed-mode PDFs into the multi-page mixed-mode PDF

```
pdftk infile.pdf burst output $tmpdir/page_%03d.pdf
page=0
imagetype="png"

for file in $tmpdir/*.pdf
do 
    image=$file.$imagetype
    convert -density $density -depth $depth $file $image
    rm $file
    page=`expr $page + 1`
    tessoptions="--tessdata-dir "$tessdatadir" -l "$language" pdf"
    tesseract $image $image $tessoptions
    rm $image
done

pdftk $tmpdir/*.pdf cat output $tmpdir/tmp.pdf
```

**Comment by jbarlow83** [comment]
In OCRmyPDF v3.0-rc2 we're now taking advantage of Tesseract's improved (single page only) PDF output to improve the overall results of OCRmyPDF. Tesseract doesn't do everything we need.

**Comment by Wikinaut** [comment]
@jbarlow83 thanks for the info.

**Comment by Wikinaut** [comment]
Apparently, the Tesseract PDF rendering mode (Tesseract versions > 3.02 can generate mixed-mode PDFs directly) which has been proposed in the present issue, can be achieved by starting OCRMyPDF with the commandline option 

`--pdf-renderer tesseract`

 (introduced in OCRMyPDf version 3.0) like in the example

```
ocrmypdf -l deu --pdf-renderer tesseract infile.pdf outfile.pdf
```

See https://github.com/fritz-hh/OCRmyPDF/blob/master/RELEASE_NOTES.rst .
@jbarlow83 Thanks for implementing this!
