### ISSUE TITLE
Script asks me to install Python 2.x although I have Python 2.7.5 installed

### ISSUE THREAD

**Issue by juancarlosfarah** [fritz-hh/OCRmyPDF#97]
I tried using the script, but when I tried to run it with the `-h` flag to see the usage, I was asked to install Python 2.x. As shown in the output below, I already have Python 2.7.5 installed.

System:
 * Mac OSX 10.9.4
 * Bash
 * Python 2.7.5
```bash
$ python --version
Python 2.7.5
````
Steps to reproduce:
1. `$ sh ./OCRmyPDF.sh -h`

Expected:
 - Script runs and shows its usage.

Actual:
> Please install python v2.x. Exiting...

**Comment by martinburch** [comment]
To get this working, the actual command I needed to use in OS X was:
`sudo ln -s /usr/bin/python /usr/bin/python2`

**Comment by jbarlow83** [comment]
Should be fixed in v3.0-rc2
