### ISSUE TITLE
Option to remove blank pages

### ISSUE THREAD

**Issue by drdownload** [fritz-hh/OCRmyPDF#98]
it would be great to have an option to remove blank pages. I scan a lot of images with my duplex scanner and not all scanned documents have a printed backside.

**Comment by zorglups** [comment]
My 2 cents. 
I scan most thing with a duplex scanner too and will implement things to remove the last page if it is blank. 

As I want to keep my PDFs a replica of documents, intermediate blank pages should remain in my archiving use.

**Comment by Wikinaut** [comment]
Just another idea:

Another (secondary) empty-page detection decision could be based on Tesseract's text output for that page (e.g. number of detected characters or the like).

**Comment by Wikinaut** [comment]
and http://superuser.com/questions/343385/detecting-blank-image-files shows alternative solutions for blank page detection.

**Comment by eloops** [comment]
One of the best ways wasn't mentioned there; I found it elsewhere. (Probably on SO as well) If you use the -verbose option of im/gm it will tell you the standard deviation of the colours in the file. Below a certain SD and you can be pretty sure it's a blank page. `empty-page` (though _really_ fast) is only good for *nix OS's, im/gm is available across a broad spectrum.

**Comment by Wikinaut** [comment]
I was looking for `empty-page`. It is part of the image utilities in ExactImage, see http://www.exactcode.com/site/open_source/exactimage/releases/
